### ISSUE TITLE
Cannot post image even though file exists

### ISSUE THREAD

**Issue by marvic2409** [stanvanrooy/instauto#47]
Here is the error I get when trying to post an image:
`images/1600543191-conf.jpeg
Traceback (most recent call last):
  File "insta.py", line 154, in <module>
    main()
  File "insta.py", line 39, in main
    postinsta(image1)
  File "insta.py", line 113, in postinsta
    resp = client.post_post(post, 80)
  File "/home/pi/.local/lib/python3.8/site-packages/instauto/api/actions/post.py", line 133, in post_post
    as_dict.pop('location')
KeyError: 'location'
None
`

The image name is image1 and it is what I printed in the very first line.

**Comment by stanvanrooy** [comment]
This should already be fixed in the latest version published to pypi: `pip install instauto --upgrade`.

**Comment by marvic2409** [comment]
I just upgraded it and I still get the error. I am on version 0.0.13

**Comment by stanvanrooy** [comment]
What does the debug logging output show? Make sure to remove any passwords etc from it.

Something like this should work to enable it:

```python
import logging 
logging.basicConfig() logging.getLogger().setLevel(logging.DEBUG)
```

**Comment by marvic2409** [comment]
It prints an issue with the google api python client, but after looking it up it seems that it is not actually an issue. Other than that I am getting the same instauto error

**Comment by marvic2409** [comment]
Yeah so I just fixed the google api issue and the only thing that now shows up is what I first reported.

**Comment by stanvanrooy** [comment]
Okay, so that means no requests to the Instagram API are actually send, so the error Instauto's processing of the request, not the response.

 Could you share the code you used to build the `Post` object?

**Comment by marvic2409** [comment]
if os.path.isfile('./.instauto.save'):
        client = ApiClient.initiate_from_file('./.instauto.save')
    else:
        client = ApiClient(user_name="username", password="password")
        client.login()
        client.save_to_disk('./.instauto.save')

    post = ps.Post.create(
        path=name,
        source_type=st.WhereToPost.Feed,
        caption=''
    )

    resp = client.post_post(post, 80)

**Comment by Danielohayon** [comment]
I am experiencing the same issue. 

I believe its because in instauto/instauto/api/actions/post.py
In line 111 location is popped:
        if as_dict['location'] is None: as_dict.pop('location')

And then in line 133 its popped again:
        as_dict.pop('location')

**Comment by stanvanrooy** [comment]
Should be fixed in V0.0.14 - released 3 minutes ago :)
